----------------------------------------------------------------------
-- This script will populate sample data in database "StudentSystem"--
----------------------------------------------------------------------

USE [StudentSystem]
GO

INSERT INTO [Towns] ([Name]) VALUES('Varna')
INSERT INTO [Towns] ([Name]) VALUES('Burgas')
INSERT INTO [Towns] ([Name]) VALUES('Sofia')
INSERT INTO [Towns] ([Name]) VALUES('Plovdiv')
INSERT INTO [Towns] ([Name]) VALUES('Ruse')
INSERT INTO [Towns] ([Name]) VALUES('Dobrich')
INSERT INTO [Towns] ([Name]) VALUES('Stara Zagora')
INSERT INTO [Towns] ([Name]) VALUES('Veliko Tarnovo')
INSERT INTO [Towns] ([Name]) VALUES('Pleven')
INSERT INTO [Towns] ([Name]) VALUES('Sozopol')
GO

INSERT INTO [Departments] ([Name]) VALUES('C# Web Development')
INSERT INTO [Departments] ([Name]) VALUES('C# Desktop Development')
INSERT INTO [Departments] ([Name]) VALUES('Java Web Development')
INSERT INTO [Departments] ([Name]) VALUES('JavaScript Web Development')
INSERT INTO [Departments] ([Name]) VALUES('Python Web Development')
GO

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Kevin_admin', '1234', 'Kevin', 'Brown', 'Bradley', 1, 1)

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Rob_teacher', '1234', 'Rob', 'Walters', 'Brown', 1, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Paula_teacher', '1234', 'Paula', 'Keil', 'Sharma', 2, 2)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Garrett_teacher', '1234', 'Garrett', 'Komosinski', 'Johnson', 3, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Susan_teacher', '1234', 'Susan', 'Michael', 'Hines', 4, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Jean_teacher', '1234', 'Jean', 'Trenary', 'Trenary', 5, 10)

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Angela', '4321', 'Angela', 'Barbariol', 'Berndt', 1, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Bryan', '4321', 'Bryan', 'Baker', 'Hay', 1, 2)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Eugene', '4321', 'Eugene', 'Zabokritski', 'Decker', 1, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Andreas', '4321', 'Andreas', 'Berglund', 'Chai', 1, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Linda', '4321', 'Linda', 'Randall', 'Hamilton', 1, 8)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Ramesh', '4321', 'Ramesh', 'Meyyappan', 'Conroy', 1, 7)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Samantha', '4321', 'Samantha', 'Smith', 'Nusbaum', 1, 10)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Denise', '4321', 'Denise', 'Brandon', 'Matthew', 1, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Alex', '4321', 'Alex', 'Singh', 'Brandon', 1, 6)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Dylan', '4321', 'Dylan', 'Miller', 'Chen', 1, 8)

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Mindy', '4321', 'Mindy', 'Moschell', 'Komosinski', 2, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Gary', '4321', 'Gary', 'Yukish', 'Petculescu', 2, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Jun', '4321', 'Jun', 'Metters', 'Metters', 2, 2)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('David', '4321', 'David', 'Ortiz', 'Feng', 2, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Annik', '4321', 'Annik', 'Stahl', 'Stahl', 2, 10)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Deborah', '4321', 'Deborah', 'Moschell', 'Scardelis', 2, 10)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Carole', '4321', 'Carole', 'Poland', 'Poland', 2, 9)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Cristian', '4321', 'Cristian', 'Petculescu', 'Bueno', 2, 9)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Janaina', '4321', 'Janaina', 'Bueno', 'Hohman', 2, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Bob', '4321', 'Bob', 'Mohamed', 'Moschell', 2, 2)

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Laura', '4321', 'Laura', 'Steele', 'Shoop', 3, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Margie', '4321', 'Margie', 'Arifin', 'Ralls', 3, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Lorraine', '4321', 'Lorraine', 'Hite', 'Metters', 3, 6)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Fadi', '4321', 'Fadi', 'Fakhouri', 'Margie', 3, 5)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Ryan', '4321', 'Ryan', 'Stahl', 'Alexander', 3, 5)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Nuan', '4321', 'Nuan', 'Yu', 'Vong', 3, 6)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Bjorn', '4321', 'Bjorn', 'Laszlo', 'Rettig', 3, 8)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Michael', '4321', 'Michael', 'Rothkugel', 'Rothkugel', 3, 7)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Lane', '4321', 'Lane', 'Sacksteder', 'Male', 3, 9)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Dan', '4321', 'Dan', 'Bacon', 'Barber', 3, 10)

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Lolan', '4321', 'Lolan', 'Nartker', 'Shoop', 4, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Mary', '4321', 'Mary', 'Gibson', 'Krapauskas', 4, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Eric', '4321', 'Eric', 'Gubbels', 'Sanchez', 4, 2)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Jason', '4321', 'Jason', 'Watters', 'Harrington', 4, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Mark', '4321', 'Mark', 'Harrington', 'Ingle', 4, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Janeth', '4321', 'Janeth', 'Esteves', 'Ingle', 4, 1)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Bjorn', '4321', 'Bjorn', 'Laszlo', 'Rettig', 4, 2)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Gigi', '4321', 'Gigi', 'Rothkugel', 'Matthew', 4, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Paul', '4321', 'Paul', 'Singh', 'Male', 4, 7)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Frank', '4321', 'Frank', 'Bacon', 'Williams', 4, 6)

INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Angela', '4321', 'Angela', 'Barbariol', 'Berndt', 5, 5)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Bryan', '4321', 'Bryan', 'Baker', 'Hay', 5, 5)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Eugene', '4321', 'Eugene', 'Zabokritski', 'Decker', 5, 10)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Andreas', '4321', 'Andreas', 'Berglund', 'Chai', 5, 9)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Linda', '4321', 'Linda', 'Randall', 'Hamilton', 5, 8)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Ramesh', '4321', 'Ramesh', 'Meyyappan', 'Conroy', 5, 7)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Samantha', '4321', 'Samantha', 'Smith', 'Nusbaum', 5, 6)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Denise', '4321', 'Denise', 'Brandon', 'Matthew', 5, 4)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Alex', '4321', 'Alex', 'Singh', 'Brandon', 5, 3)
INSERT INTO [Users] ([UserName], [Password], [FirstName], [MiddleName], [LastName], [DepartmentId], [TownId]) VALUES('Dylan', '4321', 'Dylan', 'Miller', 'Chen', 5, 2)

INSERT INTO [Administrators] ([UserId]) VALUES(1)
GO

INSERT INTO [Teachers] ([UserId]) VALUES(2)
INSERT INTO [Teachers] ([UserId]) VALUES(3)
INSERT INTO [Teachers] ([UserId]) VALUES(4)
INSERT INTO [Teachers] ([UserId]) VALUES(5)
INSERT INTO [Teachers] ([UserId]) VALUES(6)
GO

INSERT INTO [Students] ([UserId]) VALUES(7)
INSERT INTO [Students] ([UserId]) VALUES(8)
INSERT INTO [Students] ([UserId]) VALUES(9)
INSERT INTO [Students] ([UserId]) VALUES(10)
INSERT INTO [Students] ([UserId]) VALUES(11)
INSERT INTO [Students] ([UserId]) VALUES(12)
INSERT INTO [Students] ([UserId]) VALUES(13)
INSERT INTO [Students] ([UserId]) VALUES(14)
INSERT INTO [Students] ([UserId]) VALUES(15)
INSERT INTO [Students] ([UserId]) VALUES(16)
INSERT INTO [Students] ([UserId]) VALUES(17)
INSERT INTO [Students] ([UserId]) VALUES(18)
INSERT INTO [Students] ([UserId]) VALUES(19)
INSERT INTO [Students] ([UserId]) VALUES(20)
INSERT INTO [Students] ([UserId]) VALUES(21)
INSERT INTO [Students] ([UserId]) VALUES(22)
INSERT INTO [Students] ([UserId]) VALUES(23)
INSERT INTO [Students] ([UserId]) VALUES(24)
INSERT INTO [Students] ([UserId]) VALUES(25)
INSERT INTO [Students] ([UserId]) VALUES(26)
INSERT INTO [Students] ([UserId]) VALUES(27)
INSERT INTO [Students] ([UserId]) VALUES(28)
INSERT INTO [Students] ([UserId]) VALUES(29)
INSERT INTO [Students] ([UserId]) VALUES(30)
INSERT INTO [Students] ([UserId]) VALUES(31)
INSERT INTO [Students] ([UserId]) VALUES(32)
INSERT INTO [Students] ([UserId]) VALUES(33)
INSERT INTO [Students] ([UserId]) VALUES(34)
INSERT INTO [Students] ([UserId]) VALUES(35)
INSERT INTO [Students] ([UserId]) VALUES(36)
INSERT INTO [Students] ([UserId]) VALUES(37)
INSERT INTO [Students] ([UserId]) VALUES(38)
INSERT INTO [Students] ([UserId]) VALUES(39)
INSERT INTO [Students] ([UserId]) VALUES(40)
INSERT INTO [Students] ([UserId]) VALUES(41)
INSERT INTO [Students] ([UserId]) VALUES(42)
INSERT INTO [Students] ([UserId]) VALUES(43)
INSERT INTO [Students] ([UserId]) VALUES(44)
INSERT INTO [Students] ([UserId]) VALUES(45)
INSERT INTO [Students] ([UserId]) VALUES(46)
INSERT INTO [Students] ([UserId]) VALUES(47)
INSERT INTO [Students] ([UserId]) VALUES(48)
INSERT INTO [Students] ([UserId]) VALUES(49)
INSERT INTO [Students] ([UserId]) VALUES(50)
INSERT INTO [Students] ([UserId]) VALUES(51)
INSERT INTO [Students] ([UserId]) VALUES(52)
INSERT INTO [Students] ([UserId]) VALUES(53)
INSERT INTO [Students] ([UserId]) VALUES(54)
INSERT INTO [Students] ([UserId]) VALUES(55)
INSERT INTO [Students] ([UserId]) VALUES(56)
GO

INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('Fundamentals Module C#', '2020-01-12', '2020-03-07', '2020-03-01', 1)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('Entity Framework Core', '2020-03-15', '2020-06-12', '2020-06-01', 1)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('C# Advanced', '2020-05-15', '2020-06-17', '2020-06-12', 1)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('C# OOP', '2020-07-11', '2020-09-15', '2020-09-12', 1)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('ASP.NET Core', '2020-09-07', '2020-11-13', '2020-11-12', 1)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('Fundamentals WPF', '2019-12-12', '2020-03-07', '2020-03-01', 2)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('Fundamentals Module Java', '2019-12-12', '2020-03-07', '2020-03-01', 3)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('Fundamentals Module Pyton', '2019-12-12', '2020-03-07', '2020-03-01', 4)
INSERT INTO [Courses] ([Name], [StartDate], [EndDate], [ExamDate], [TeacherId]) VALUES('Fundamentals Module JavaScript', '2019-12-12', '2020-03-07', '2020-03-01', 5)
GO

INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(1, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(1, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(1, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(1, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(1, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(2, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(2, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(2, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(2, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(2, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(3, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(3, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(3, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(3, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(3, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(4, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(4, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(4, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(4, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(4, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(5, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(5, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(5, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(5, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(5, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(6, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(6, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(6, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(6, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(6, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(7, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(7, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(7, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(7, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(7, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(8, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(8, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(8, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(8, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(8, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(9, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(9, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(9, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(9, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(9, 5)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(10, 1)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(10, 2)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(10, 3)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(10, 4)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(10, 5)

INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(11, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(12, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(13, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(14, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(15, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(16, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(17, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(19, 6)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(20, 6)

INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(21, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(22, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(23, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(24, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(25, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(26, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(27, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(29, 7)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(30, 7)

INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(31, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(32, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(33, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(34, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(35, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(36, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(37, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(39, 8)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(40, 8)

INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(41, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(42, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(43, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(44, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(45, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(46, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(47, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(49, 9)
INSERT INTO [StudentCourses] ([StudentId], [CourseId]) VALUES(50, 9)